modLoader="kotlinfml"
loaderVersion="[1.4,)"

issueTrackerURL="https://github.com/AngrySoundTech/ForgeKotlinTemplate/issues"
displayURL="https://github.com/AngrySoundTech/ForgeKotlinTemplate"
authors="AngrySoundTech"
credits=""

[[mods]]
modId="forgekotlintemplate"
version="${version}"
displayName="ForgeKotlinTemplate"
description=""

[[dependencies.forgekotlintemplate]]
modId="forge"
mandatory=true
versionRange="[28.1.92,)"
ordering="NONE"
side="BOTH"
