modLoader="kotlinfml"
loaderVersion="[1.4,)"

issueTrackerURL="https://github.com/AngrySoundTech/SignCipher/issues"
displayURL="https://github.com/AngrySoundTech/SignCipher"
authors="AngrySoundTech"
credits=""

[[mods]]
modId="signcipher"
version="${version}"
displayName="SignCipher"
description=""

[[dependencies.signcipher]]
modId="forge"
mandatory=true
versionRange="[28.1.92,)"
ordering="NONE"
side="BOTH"
