modLoader="kotlinfml"
loaderVersion="[1.4,)"

issueTrackerURL="https://github.com/AngrySoundTech/SignPad/issues"
displayURL="https://github.com/AngrySoundTech/SignPad"
authors="AngrySoundTech"
credits=""

[[mods]]
modId="signpad"
version="${version}"
displayName="SignPad"
description=""

[[dependencies.signpad]]
modId="forge"
mandatory=true
versionRange="[28.1.92,)"
ordering="NONE"
side="BOTH"
